name: 'Terraform'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    env:
      STATE_BUCKET: "my-production-state-bucket-unique-123"
      AWS_REGION: "us-east-1"
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Check AWS Identity
      run: |
        aws sts get-caller-identity
        aws ec2 describe-key-pairs --region us-east-1
    - name: Bootstrap S3 State Bucket
      run: |
        echo "Checking if S3 bucket $STATE_BUCKET exists..."

        if aws s3api head-bucket --bucket "$STATE_BUCKET" 2>/dev/null; then
            echo "Bucket already exists. Skipping creation."
        else
            echo "Bucket does not exist. Creating it now..."

            aws s3api create-bucket \
              --bucket "$STATE_BUCKET" \
              --region "$AWS_REGION"

            aws s3api put-bucket-versioning \
              --bucket "$STATE_BUCKET" \
              --versioning-configuration Status=Enabled

            echo "Bucket created and versioning enabled!"
        fi
    - name: Terraform Init
      run: |
        terraform init \
          -reconfigure \
          -backend-config="bucket=${STATE_BUCKET}" \
          -backend-config="key=sample-app/terraform.tfstate" \
          -backend-config="region=${AWS_REGION}"

    - name: Terraform Format
      run: terraform fmt -check -diff

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -input=false
   
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        terraform apply -auto-approve -input=false
